In [3]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
data=pd.read_csv('heart.csv')
data.head()
data.shape

(1025, 14)

# 1. Import The Libraries And Dataset
2. Display Top 5 Rows of The Dataset
3. Check The Last 5 Rows of The Dataset
4. Find Shape of Our Dataset (Number of Rows And Number of Columns)
5. Get Information About Our Dataset Like Total Number Rows, Total Number of Columns, Datatypes of Each Column And Memory Requirement
6. Check Null Values In The Dataset
7. Check For Duplicate Data and Drop Them
8. Get Overall Statistics About The Dataset
9. Draw Correlation Matrix 
10. How Many People Have Heart Disease, And How Many Don't Have Heart Disease In This Dataset?
11. Find Count of  Male & Female in this Dataset
12. Find Gender Distribution According to The Target Variable
13. Check Age Distribution In The Dataset
14. Check Chest Pain Type
15. Show The Chest Pain Distribution As Per Target Variable
16. Show Fasting Blood Sugar Distribution According To Target Variable
17.  Check Resting Blood Pressure Distribution
18. Compare Resting Blood Pressure As Per Sex Column
19. Show Distribution of Serum cholesterol
20. Plot Continuous Variables

In [2]:
data.tail()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
1020   59    1   1       140   221    0        1      164      1      0.0   
1021   60    1   0       125   258    0        0      141      1      2.8   
1022   47    1   0       110   275    0        0      118      1      1.0   
1023   50    0   0       110   254    0        0      159      0      0.0   
1024   54    1   0       120   188    0        1      113      0      1.4   

      slope  ca  thal  target  
1020      2   0     2       1  
1021      1   1     3       0  
1022      1   1     2       0  
1023      2   0     2       1  
1024      1   1     3       0

In [3]:
data.describe()

age          sex           cp     trestbps        chol  \
count  1025.000000  1025.000000  1025.000000  1025.000000  1025.00000   
mean     54.434146     0.695610     0.942439   131.611707   246.00000   
std       9.072290     0.460373     1.029641    17.516718    51.59251   
min      29.000000     0.000000     0.000000    94.000000   126.00000   
25%      48.000000     0.000000     0.000000   120.000000   211.00000   
50%      56.000000     1.000000     1.000000   130.000000   240.00000   
75%      61.000000     1.000000     2.000000   140.000000   275.00000   
max      77.000000     1.000000     3.000000   200.000000   564.00000   

               fbs      restecg      thalach        exang      oldpeak  \
count  1025.000000  1025.000000  1025.000000  1025.000000  1025.000000   
mean      0.149268     0.529756   149.114146     0.336585     1.071512   
std       0.356527     0.527878    23.005724     0.472772     1.175053   
min       0.000000     0.000000    71.000000     0.000000     0.000000   
25%       0.000000     0.000000   132.000000     0.000000     0.000000   
50%       0.000000     1.000000   152.000000     0.000000     0.800000   
75%       0.000000     1.000000   166.000000     1.000000     1.800000   
max       1.000000     2.000000   202.000000     1.000000     6.200000   

             slope           ca         thal       target  
count  1025.000000  1025.000000  1025.000000  1025.000000  
mean      1.385366     0.754146     2.323902     0.513171  
std       0.617755     1.030798     0.620660     0.500070  
min       0.000000     0.000000     0.000000     0.000000  
25%       1.000000     0.000000     2.000000     0.000000  
50%       1.000000     0.000000     2.000000     1.000000  
75%       2.000000     1.000000     3.000000     1.000000  
max       2.000000     4.000000     3.000000     1.000000

In [ ]:
data.isnull().sum()

In [ ]:
data['target'].value_counts()

In [6]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,

In [7]:
X=data.drop(columns='target',axis=1)
y=data['target']

In [8]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2 ,stratify=y,random_state=3)

In [9]:
print(X.shape,X_train.shape,X_test.shape,y_train.shape,y_test.shape)

(1025, 13) (820, 13) (205, 13) (820,) (205,)


In [10]:
model=LogisticRegression()

In [11]:
model.fit(X_train,y_train)

C:\Users\Admin\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [34]:
X_train_prediction=model.predict(X_train)
Training_data_accuracy=accuracy_score(X_train_prediction,y_train)
print("Training_data_accuracy-",Training_data_accuracy)

Training_data_accuracy- 0.8597560975609756


In [35]:
X_test_prediction=model.predict(X_test)
Test_data_accuracy=accuracy_score(X_test_prediction,y_test)
print('Test_data_accuracy-',Test_data_accuracy)

Test_data_accuracy- 0.8390243902439024


In [18]:
from sklearn.metrics import accuracy_score,confusion_matrix
print("Accuracy of Logistic Regression",accuracy_score(X_test_prediction,y_test))

Accuracy of Logistic Regression 0.8390243902439024


In [19]:
confusion_matrix(X_test_prediction,y_test)

array([[79, 12],
       [21, 93]], dtype=int64)

In [23]:
print("Logistic Regression Confusion Matrix\n")
pd.DataFrame(confusion_matrix(X_test_prediction,y_test),columns=list(range(0,2)))

Logistic Regression Confusion Matrix



0   1
0  79  12
1  21  93

In [70]:
result = pd.DataFrame()
result['Actual Label'] = y_test
result['Logistic Regression Prediction'] = X_test_prediction

In [72]:
result.sample(3)

Actual Label  Logistic Regression Prediction
280             1                               1
84              1                               1
857             1                               0

In [73]:
result1 = pd.DataFrame()
result1['Actual Label'] = y_train
result1['Logistic Regression Prediction'] = X_train_prediction

In [75]:
result1.sample(5)
result1.shape

(820, 2)

In [27]:
from sklearn.metrics import recall_score,precision_score,f1_score

In [28]:
print("For Logistic regression Model")
print("-"*50)
cdf = pd.DataFrame(confusion_matrix(y_test,X_test_prediction),columns=list(range(0,2)))
print(cdf)
print("-"*50)
print("Precision - ",precision_score(y_test,X_test_prediction))
print("Recall - ",recall_score(y_test,X_test_prediction))
print("F1 score - ",f1_score(y_test,X_test_prediction))

For Logistic regression Model
--------------------------------------------------
    0   1
0  79  21
1  12  93
--------------------------------------------------
Precision -  0.8157894736842105
Recall -  0.8857142857142857
F1 score -  0.8493150684931505


In [30]:
precision_score(y_test,X_test_prediction,average=None)

array([0.86813187, 0.81578947])

In [31]:
recall_score(y_test,X_test_prediction,average=None)

array([0.79      , 0.88571429])

In [57]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn import svm
from sklearn.metrics import recall_score,precision_score,f1_score
from sklearn.metrics import accuracy_score

In [58]:
X=data.drop(columns='target',axis=1)
y=data['target']

In [68]:
scaler=StandardScaler()
scaler.fit(X)
standardzied_data=scaler.transform(X)
print(standardzied_data)


array([[-0.26843658,  0.66150409, -0.91575542, ...,  0.99543334,
         1.20922066,  1.08985168],
       [-0.15815703,  0.66150409, -0.91575542, ..., -2.24367514,
        -0.73197147,  1.08985168],
       [ 1.71659547,  0.66150409, -0.91575542, ..., -2.24367514,
        -0.73197147,  1.08985168],
       ...,
       [-0.81983438,  0.66150409, -0.91575542, ..., -0.6241209 ,
         0.23862459, -0.52212231],
       [-0.4889957 , -1.51170646, -0.91575542, ...,  0.99543334,
        -0.73197147, -0.52212231],
       [-0.04787747,  0.66150409, -0.91575542, ..., -0.6241209 ,
         0.23862459,  1.08985168]])

In [60]:
X=standardzied_data
y=data['target']

In [61]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2 ,stratify=y,random_state=1)

In [62]:
print(X.shape,X_train.shape,X_test.shape,y_train.shape,y_test.shape)

(1025, 13) (820, 13) (205, 13) (820,) (205,)


In [63]:
classifier=svm.SVC(kernel='linear',C=.1)
classifier.fit(X_train,y_train)

SVC(C=0.1, kernel='linear')

In [64]:
X_train_prediction=model.predict(X_train)
Training_data_accuracy=accuracy_score(X_train_prediction,y_train)
print("Training_data_accuracy-",Training_data_accuracy)

Training_data_accuracy- 0.824390243902439


C:\Users\Admin\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


In [65]:
X_test_prediction=model.predict(X_test)
Test_data_accuracy=accuracy_score(X_test_prediction,y_test)
print('Test_data_accuracy-',Test_data_accuracy)

Test_data_accuracy- 0.8341463414634146


C:\Users\Admin\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


In [14]:
import numpy as np
input_data=(43,0,0,132,341,1,0,136,1,3,1,0,3)
input_data_as_numpy_array=np.asarray(input_data)
input_data_reshape=input_data_as_numpy_array.reshape(1,-1)
prediction=model.predict(input_data_reshape)
print(prediction)

[0]


C:\Users\Admin\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


In [15]:

if prediction[0]==0:
    print('The person does not Heart disease' )
else:
    print('The person has Heart disease ')

The person does not Heart disease
